logging:
  level:
    root: INFO
    org.springframework: INFO
    io.terminus.session: ERROR
    com.alibaba.dubbo: ERROR
    com.pousheng: DEBUG
  file:
    path: logs

server:
  port: 8888

# 多数据源配置，采用最简单的多套源策略
spring:
  datasource:
    db1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: root
      password: 123456
      continue-on-error: false
    db2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: root
      password: 123456
      continue-on-error: false

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
   io.terminus.parana.(item|shop|category|spu|brand|delivery).model,
   com.pousheng.item.model,com.pousheng.shop.model,com.pousheng.stuffybag.model

# 微软云配置
azure:
  oss:
    defaultEndpointsProtocol: https
    accountName: f2wossfilehdd
    accountKey: GiDg58DcAx8fLBQYqhjnMmKiOgHntWlexP1ZIDwCIdOEQr/IuAl6NQiy6m7Zl+rSU6ynxUJXufAEGYG3+NB2MQ==
    endpointSuffix: core.chinacloudapi.cn